---
title: "SNV Mutation Burden vs Age"
output:
  pdf_document: default
  html_notebook: default
---

#Load Libraries
```{r}
library("ggplot2")
library("reshape2")
library("RColorBrewer")
library("plyr")
library("dplyr")
library("lme4")
library("nlme")
library(lmerTest)
library("tidyverse")
library("ggpubr")
library("gridExtra")
library("cowplot")
library(stats)
library(MASS)
library(jtools)
library("patchwork")
library("ggthemes")
library(viridis)
library(lmtest)
options(scipen = 999)
theme_set(theme_cowplot())

```

#Load Data
```{r}

mycolors <- c("PD42034(33.6)" = "#A6CEE3", "PD42563(38)" = "#3385BB", "PD40744(30)" = "#84BF96", "PD46269(22)" = "#6DBD57", "PD42036(28.3)" = "#7F9D55", "PD42569(44)" = "#F57C7C", "PD42566(48)" = "#E42622", "PD42565/PD43851(47)" = "#FBB268", "PD40745/PD42564(46)" = "#FE8D19", "PD40746/PD42568(71)" = "#DE9E83", "PD28690(78)" = "#977899", "PD43727(60.6)" = "#F3E587", "PD43726(82.8)" = "#B15928", "PD42034" = "#A6CEE3", "PD42563" = "#3385BB", "PD40744" = "#84BF96", "PD46269" = "#6DBD57", "PD42036" = "#7F9D55", "PD42569" = "#F57C7C", "PD42566" = "#E42622", "PD42565/PD43851" = "#FBB268", "PD40745/PD42564" = "#FE8D19", "PD40746/PD42568" = "#DE9E83", "PD28690" = "#977899", "PD43727" = "#F3E587", "PD43726" = "#B15928", "PD43850" = "#EED393", "PD43850(54)" = "#EED393")

Mutations_avgCov_per_sample_withpanBody <- read.table("/Users/rs30/volumes/rs30_lustre/rs30-117/Pan_body/Mutational_burden/Mutations_per_sample_used_for_models.txt", header=T, check.names=FALSE, sep="\t", quote = "")

load("/Users/rs30/volumes/rs30_lustre/rs30-117/Pan_body/Final_Files/sorting_list.RData")

Mutations_avgCov_per_sample_withpanBody$Sensitivity <- Mutations_avgCov_per_sample_withpanBody$sample.median.vaf*Mutations_avgCov_per_sample_withpanBody$Seq_X
unique(Mutations_avgCov_per_sample_withpanBody$DonorID)

#To exclude samples with <15X coverage
Mutations_avgCov_per_sample_withpanBody <- Mutations_avgCov_per_sample_withpanBody[which(Mutations_avgCov_per_sample_withpanBody$Seq_X > 15),]

Mutations_avgCov_per_sample_withpanBody_Testis <- Mutations_avgCov_per_sample_withpanBody[which(Mutations_avgCov_per_sample_withpanBody$TissueType1 %in%  c("testis")),]
unique(Mutations_avgCov_per_sample_withpanBody_Testis$TissueType1)


Mutations_avgCov_per_sample_withpanBody_colon <- Mutations_avgCov_per_sample_withpanBody[which(Mutations_avgCov_per_sample_withpanBody$TissueType1 %in%  c("colon")),]
unique(Mutations_avgCov_per_sample_withpanBody_colon$TissueType1)

Mutations_avgCov_per_sample_withpanBody_Testis_clonal <- Mutations_avgCov_per_sample_withpanBody_Testis[which(!is.na(Mutations_avgCov_per_sample_withpanBody_Testis$Burden_clonal2)),]
unique(Mutations_avgCov_per_sample_withpanBody_Testis_clonal$DonorID)

Mutations_avgCov_per_sample_withpanBody_colon_clonal <- Mutations_avgCov_per_sample_withpanBody_colon[which(!is.na(Mutations_avgCov_per_sample_withpanBody_colon$Burden_clonal2)),]
unique(Mutations_avgCov_per_sample_withpanBody_colon_clonal$DonorID)
```

```{r}
## Linear model
mod_withVAFseqX <- lm(as.integer(Clonal_Mutations_per_genome2) ~ as.integer(Age)+Sensitivity , data = Mutations_avgCov_per_sample_withpanBody_Testis_clonal)
a <- signif(coef(mod_withVAFseqX)[1], digits = 2)
b <- signif(coef(mod_withVAFseqX)[2], digits = 2)
c <- signif(coef(mod_withVAFseqX)[3], digits = 2)
textlab_VAFseqX <- paste("Mutations_per_genome = ",a," + ", b,"*Age", sep = "")
print(summ(mod_withVAFseqX))
summary(mod_withVAFseqX)
anova(mod_withVAFseqX, test="Chisq")
coef(mod_withVAFseqX)
plot(mod_withVAFseqX)
print(textlab_VAFseqX)
confint(mod_withVAFseqX, 'as.integer(Age)', level=0.95)
```


```{r}

mod_withVAF <- lm(as.integer(Clonal_Mutations_per_genome2) ~ as.integer(Age) + sample.median.vaf , data = Mutations_avgCov_per_sample_withpanBody_Testis_clonal)
a <- signif(coef(mod_withVAF)[1], digits = 2)
b <- signif(coef(mod_withVAF)[2], digits = 2)
c <- signif(coef(mod_withVAF)[3], digits = 2)
textlab_VAF <- paste("Mutations_per_genome = ",a," + ", b,"*Age", sep = "")
print(summ(mod_withVAF))
summary(mod_withVAF)
anova(mod_withVAF, test="Chisq")
coef(mod_withVAF)
plot(mod_withVAF)
print(textlab_VAF)
confint(mod_withVAF, 'as.integer(Age)', level=0.95)
lrtest(mod_withVAF, mod_withVAFseqX)
#mod_withVAFseqX is better 
```

```{r}
## Linear Mixed effect model
mod_withVAF_mixedeffect_SampleID <- lmer(as.integer(Clonal_Mutations_per_genome2) ~ as.integer(Age)+offset(Sensitivity) + (1|DonorID), data = Mutations_avgCov_per_sample_withpanBody_Testis_clonal, REML = FALSE)
print(summ(mod_withVAF_mixedeffect_SampleID))
anova(mod_withVAF_mixedeffect_SampleID, test="Chisq")
plot(mod_withVAF_mixedeffect_SampleID)
coef(mod_withVAF_mixedeffect_SampleID)

coeffecient <- coef(mod_withVAF_mixedeffect_SampleID)
intercept <- signif(mean(coeffecient$DonorID$`(Intercept)`), digits = 2)
slope <- signif(mean(coeffecient$DonorID$`as.integer(Age)`), digits = 2)
textlab_lmer_model <- paste("Mutations_per_genome = ",intercept," + ", slope,"*Age", sep = "")

print(textlab_lmer_model)
confint(mod_withVAF_mixedeffect_SampleID, 'as.integer(Age)', level=0.95)
lrtest(mod_withVAFseqX, mod_withVAF_mixedeffect_SampleID)
#mod_withVAF_mixedeffect_SampleID is better 
```


```{r}
## Generalized model with Poisson
mod_withVAF_glmer_SampleID <- glmer(as.integer(Clonal_Mutations_per_genome2) ~ as.integer(Age) + offset(log(Sensitivity)) + (1|DonorID)  , data = Mutations_avgCov_per_sample_withpanBody_Testis_clonal, family = poisson(link = "log"))
plot(mod_withVAF_glmer_SampleID)
anova(mod_withVAF_glmer_SampleID, test="Chisq")
summary(mod_withVAF_glmer_SampleID)
coef(mod_withVAF_glmer_SampleID)

coeffecient <- coef(mod_withVAF_glmer_SampleID)
intercept <- signif(exp(mean(coeffecient$`DonorID`$`(Intercept)`)), digits = 2)
slope <- signif(exp(mean(coeffecient$`DonorID`$`as.integer(Age)`)), digits = 2)
textlab_glmer_model <- paste("Mutations_per_genome = ",intercept," + ", slope,"*Age", sep = "")
print(textlab_glmer_model)
```


```{r}

Mutations_avgCov_per_sample_withpanBody_Testis_clonal$DonorID <- factor(Mutations_avgCov_per_sample_withpanBody_Testis_clonal$DonorID, levels = age_sort$DonorID)

p_model <- ggplot()+ geom_boxplot(data=Mutations_avgCov_per_sample_withpanBody_Testis_clonal, aes(x = Age, y = Clonal_Mutations_per_genome2, fill=DonorID),width=1.5, outlier.shape = NA,position=position_dodge2()) + geom_dotplot(data=Mutations_avgCov_per_sample_withpanBody_Testis_clonal, aes(x = Age, y = Clonal_Mutations_per_genome2, fill=DonorID), binaxis='y', stackdir='center', position=position_dodge(1.5),dotsize = 0.25)+ stat_summary(fun.y=mean, colour="darkred", geom="point", shape=19, size=1,show.legend = FALSE) + geom_smooth(data=Mutations_avgCov_per_sample_withpanBody_Testis_clonal, aes(x = as.numeric(Age), y = Clonal_Mutations_per_genome2),color="black",method=lm, se=T) +xlab("Age(years)") + ylab("Number of Mutations(SNVs)") + scale_fill_manual(values = mycolors, name="Sample")  + theme_pubr()+theme(legend.position = "right", legend.title=element_text(size=10), legend.text=element_text(size=8), legend.direction = "vertical")+guides(fill=guide_legend(ncol=1,byrow=TRUE))+annotate("text", x = 1, y = 375, label = print(textlab_lmer_model), color="black", size = 4, parse=FALSE, hjust=0)+coord_cartesian(xlim=c(0,100), ylim=c(0,400),  expand=FALSE)

p_model



```

## For Colon
```{r}
## Linear model 
Mutations_avgCov_per_sample_withpanBody_colon$Sensitivity <- Mutations_avgCov_per_sample_withpanBody_colon$sample.median.vaf*Mutations_avgCov_per_sample_withpanBody_colon$Seq_X
mod_withVAFseqX_colon <- lm(as.integer(Mutations_per_genome) ~ as.integer(Age)+Sensitivity , data = Mutations_avgCov_per_sample_withpanBody_colon)
a <- signif(coef(mod_withVAFseqX_colon)[1], digits = 2)
b <- signif(coef(mod_withVAFseqX_colon)[2], digits = 2)
c <- signif(coef(mod_withVAFseqX_colon)[3], digits = 2)
textlab_VAFseqX_colon <- paste("Mutations_per_genome = ",a," + ", b,"*Age", sep = "")
print(summ(mod_withVAFseqX_colon))
summary(mod_withVAFseqX_colon)
anova(mod_withVAFseqX_colon, test="Chisq")
coef(mod_withVAFseqX_colon)
plot(mod_withVAFseqX_colon)
print(mod_withVAFseqX_colon)
confint(mod_withVAFseqX_colon, 'as.integer(Age)', level=0.95)
```


```{r}

mod_withVAF_colon <- lm(as.integer(Mutations_per_genome) ~ as.integer(Age) + sample.median.vaf , data = Mutations_avgCov_per_sample_withpanBody_colon)
a <- signif(coef(mod_withVAF_colon)[1], digits = 2)
b <- signif(coef(mod_withVAF_colon)[2], digits = 2)
c <- signif(coef(mod_withVAF_colon)[3], digits = 2)
textlab_VAF_colon <- paste("Mutations_per_genome = ",a," + ", b,"*Age", sep = "")
print(summ(mod_withVAF_colon))
summary(mod_withVAF_colon)
anova(mod_withVAF_colon, test="Chisq")
coef(mod_withVAF_colon)
plot(mod_withVAF_colon)
print(mod_withVAF_colon)
confint(mod_withVAF_colon, 'as.integer(Age)', level=0.95)
lrtest(mod_withVAF_colon, mod_withVAFseqX)
#mod_withVAFseqX is better 
```

```{r}
## Linear Mixed effect model
mod_withVAF_mixedeffect_SampleID_colon <- lmer(as.integer(Clonal_Mutations_per_genome2) ~ as.integer(Age)+offset(Sensitivity) + (1|DonorID), data = Mutations_avgCov_per_sample_withpanBody_colon_clonal, REML = FALSE)
print(summ(mod_withVAF_mixedeffect_SampleID_colon))
anova(mod_withVAF_mixedeffect_SampleID_colon, test="Chisq")
plot(mod_withVAF_mixedeffect_SampleID_colon)
coef(mod_withVAF_mixedeffect_SampleID_colon)

coeffecient <- coef(mod_withVAF_mixedeffect_SampleID_colon)
intercept <- signif(mean(coeffecient$DonorID$`(Intercept)`), digits = 2)
slope <- signif(mean(coeffecient$DonorID$`as.integer(Age)`), digits = 2)
textlab_lmer_model_colon <- paste("Mutations_per_genome = ",intercept," + ", slope,"*Age", sep = "")

print(textlab_lmer_model_colon)
confint(mod_withVAF_mixedeffect_SampleID_colon, 'as.integer(Age)', level=0.95)
lrtest(mod_withVAFseqX_colon, mod_withVAF_mixedeffect_SampleID_colon)
#mod_withVAF_mixedeffect_SampleID_colon is better 

```


```{r}

p_model_colon <- ggplot()+ geom_boxplot(data=Mutations_avgCov_per_sample_withpanBody_colon_clonal, aes(x = Age, y = Clonal_Mutations_per_genome2, fill=DonorID),width=1.5, outlier.shape = NA,position=position_dodge2()) + geom_dotplot(data=Mutations_avgCov_per_sample_withpanBody_colon_clonal, aes(x = Age, y = Clonal_Mutations_per_genome2, fill=DonorID), binaxis='y', stackdir='center', position=position_dodge(1.5),dotsize = 0.25)+ stat_summary(fun.y=mean, colour="darkred", geom="point", shape=19, size=1,show.legend = FALSE) + geom_smooth(data=Mutations_avgCov_per_sample_withpanBody_colon_clonal, aes(x = as.numeric(Age), y = Clonal_Mutations_per_genome2),color="black",method=lm, se=T) +xlab("Age(years)") + ylab("Number of Mutations(SNVs)") + scale_fill_manual(values = mycolors, name="Sample")  + theme_pubr()+theme(legend.position = "right", legend.title=element_text(size=10), legend.text=element_text(size=8), legend.direction = "vertical")+guides(fill=guide_legend(ncol=1,byrow=TRUE))+annotate("text", x = 1, y = 6000, label = print(textlab_lmer_model_colon), color="black", size = 4, parse=FALSE, hjust=0)

p_model_colon



```

# Colon fold accumulation
```{r}

Mutations_avgCov_per_sample_withpanBody_Testis_colon <- Mutations_avgCov_per_sample_withpanBody[which(Mutations_avgCov_per_sample_withpanBody$TissueType1 %in%  c("testis","colon")),]
unique(Mutations_avgCov_per_sample_withpanBody_Testis_colon$TissueType1)
Mutations_avgCov_per_sample_withpanBody_Testis_colon <- Mutations_avgCov_per_sample_withpanBody_Testis_colon[which(Mutations_avgCov_per_sample_withpanBody_Testis_colon$DonorID %in%  unique(Mutations_avgCov_per_sample_withpanBody_Testis_colon[which(Mutations_avgCov_per_sample_withpanBody_Testis_colon$TissueType1 == "colon" & Mutations_avgCov_per_sample_withpanBody_Testis_colon$DonorID != "PD43850"), "DonorID"])),] 
rownames(Mutations_avgCov_per_sample_withpanBody_Testis_colon) <- NULL
Mutations_avgCov_per_sample_withpanBody_Testis_colon$TissueType1 <- factor(Mutations_avgCov_per_sample_withpanBody_Testis_colon$TissueType1, levels = c("colon", "testis"))
Mutations_avgCov_per_sample_withpanBody_Testis_colon$TissueType4 <- factor(Mutations_avgCov_per_sample_withpanBody_Testis_colon$TissueType4, levels = c("colon_crypt", "testis_seminiferous_tubule"))
Mutations_avgCov_per_sample_withpanBody_Testis_colon$DonorID <- factor(Mutations_avgCov_per_sample_withpanBody_Testis_colon$DonorID, levels= unique(Mutations_avgCov_per_sample_withpanBody_Testis_colon$DonorID))
Mutations_avgCov_per_sample_withpanBody_Testis_colon$Sample <- factor(Mutations_avgCov_per_sample_withpanBody_Testis_colon$Sample, levels= unique(Mutations_avgCov_per_sample_withpanBody_Testis_colon$Sample))
Mutations_avgCov_per_sample_withpanBody_Testis_colon$SampleTissue <- factor(Mutations_avgCov_per_sample_withpanBody_Testis_colon$SampleTissue, levels= unique(Mutations_avgCov_per_sample_withpanBody_Testis_colon$SampleTissue))

## Linear model 
mod_withVAF <- lm(as.integer(Mutations_per_genome) ~ as.integer(Age) + sample.median.vaf + TissueType1, data = Mutations_avgCov_per_sample_withpanBody_Testis_colon)
a <- signif(coef(mod_withVAF)[1], digits = 2)
b <- signif(coef(mod_withVAF)[2], digits = 2)
c <- signif(coef(mod_withVAF)[3], digits = 2)
textlab_VAF <- paste("Mutations_per_genome = ",a," + ", b,"*Age", sep = "")
print(summ(mod_withVAF))
summary(mod_withVAF)
anova(mod_withVAF, test="Chisq")
coef(mod_withVAF)
plot(mod_withVAF)
print(textlab_VAF)
confint(mod_withVAF, 'as.integer(Age)', level=0.95)

summary(Mutations_avgCov_per_sample_withpanBody_Testis_colon)
mod_withVAF_mixedeffect_SampleID <- lmer(as.integer(Mutations_per_genome) ~ as.integer(Age)+offset(sample.median.vaf*Seq_X) + (1+TissueType1|DonorID), data = Mutations_avgCov_per_sample_withpanBody_Testis_colon, REML = FALSE)
print(summ(mod_withVAF_mixedeffect_SampleID))
summary(mod_withVAF_mixedeffect_SampleID)
anova(mod_withVAF_mixedeffect_SampleID, test="Chisq")
plot(mod_withVAF_mixedeffect_SampleID)
coef(mod_withVAF_mixedeffect_SampleID)

coeffecient_colon <- coef(mod_withVAF_mixedeffect_SampleID)
intercept_colon <- signif(mean(coeffecient_colon$DonorID$`(Intercept)`), digits = 2)
slope_colon <- signif(mean(coeffecient_colon$DonorID$`as.integer(Age)`), digits = 2)
textlab_lmer_model_colon <- paste("Mutations_per_genome = ",intercept_colon," + ", slope_colon,"*Age", sep = "")
print(textlab_lmer_model_colon)
confint(mod_withVAF_mixedeffect_SampleID, 'as.integer(Age)', level=0.95)

fold_diff <- as.data.frame(unique(Mutations_avgCov_per_sample_withpanBody_Testis_colon$DonorID))
colnames(fold_diff) <- c("DonorID")

for(i in unique(Mutations_avgCov_per_sample_withpanBody_Testis_colon$DonorID)){
  print(paste(i,  round(median(Mutations_avgCov_per_sample_withpanBody_Testis_colon[which(Mutations_avgCov_per_sample_withpanBody_Testis_colon$DonorID == i & Mutations_avgCov_per_sample_withpanBody_Testis_colon$TissueType1 == "colon"),"Mutations_per_genome"]), digits = 2), round(median(Mutations_avgCov_per_sample_withpanBody_Testis_colon[which(Mutations_avgCov_per_sample_withpanBody_Testis_colon$DonorID == i & Mutations_avgCov_per_sample_withpanBody_Testis_colon$TissueType1 == "testis"),"Mutations_per_genome"]), digits = 2), unique(Mutations_avgCov_per_sample_withpanBody_Testis_colon[which(Mutations_avgCov_per_sample_withpanBody_Testis_colon$DonorID == i),"Age"]),  sep=" "))
  fold_diff[which(fold_diff$DonorID == i), "Median_colon"] <- round(median(Mutations_avgCov_per_sample_withpanBody_Testis_colon[which(Mutations_avgCov_per_sample_withpanBody_Testis_colon$DonorID == i & Mutations_avgCov_per_sample_withpanBody_Testis_colon$TissueType1 == "colon"),"Mutations_per_genome"]), digits = 2)
  fold_diff[which(fold_diff$DonorID == i), "Median_testis"] <- round(median(Mutations_avgCov_per_sample_withpanBody_Testis_colon[which(Mutations_avgCov_per_sample_withpanBody_Testis_colon$DonorID == i & Mutations_avgCov_per_sample_withpanBody_Testis_colon$TissueType1 == "testis"),"Mutations_per_genome"]), digits = 2)
  fold_diff[which(fold_diff$DonorID == i), "Age"] <- unique(Mutations_avgCov_per_sample_withpanBody_Testis_colon[which(Mutations_avgCov_per_sample_withpanBody_Testis_colon$DonorID == i),"Age"])
}

wilcox.test(fold_diff$Median_colon, fold_diff$Median_testis, alternative="greater", paired = TRUE)

```
